controllers/SiteController.php
<?php
namespace app\controllers;
use app\models\ContactForm;
use app\models\LoginForm;
use app\models\Tiket;
use Yii;
use yii\db\Expression;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\Response;
class SiteController extends Controller {
	/**
	 * {@inheritdoc}
	 */
	public function behaviors() {
		return [
			'access' => [
				'class' => AccessControl::className(),
				'only'  => [ 'logout' ],
				'rules' => [
					[
						'actions' => [ 'logout' ],
						'allow'   => true,
						'roles'   => [ '@' ],
					],
				],
			],
			'verbs'  => [
				'class'   => VerbFilter::className(),
				'actions' => [
					'logout' => [ 'post' ],
				],
			],
		];
	}
	/**
	 * {@inheritdoc}
	 */
	public function actions() {
		return [
			'error'   => [
				'class' => 'yii\web\ErrorAction',
			],
			'captcha' => [
				'class'           => 'yii\captcha\CaptchaAction',
				'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
			],
		];
	}
	/**
	 * Displays homepage.
	 *
	 * @return string
	 */
	public function actionIndex() {
		$session = Yii::$app->session;
		$session->open();
		if ( isset( $_GET[ 'oper' ] ) && $_GET[ 'oper' ] == 'flush' ) {
			$session->destroy();
		}
		if ( Yii::$app->request->isPost ) {
			$session->set( 'tourSelect', $_POST[ 'tour-select' ] );
		}
		$tourSelect    = $session->has( 'tourSelect' ) ? $session->get( 'tourSelect' ) : 'Adiluhung Mataram';
		$session->set( 'tourSelect', $tourSelect);
		$peopleSelect  = $session->has( 'peopleSelect' ) ? $session->get( 'peopleSelect' ) : 1;
		$ticketDate    = $session->has( 'ticketDate' ) ? $session->get( 'ticketDate' ) : date( 'Y-m-d' );
		$ticketTime    = $session->has( 'ticketTime' ) ? $session->get( 'ticketTime' ) : date( 'H:i' );
		$ticketDateMin = date( 'Y-m-d', strtotime( '+1 days' ) );
		if ( isset( $_GET[ 'mode' ] ) && $_GET[ 'mode' ] == 'admin' ) {
			$ticketDateMin = date( 'Y-m-d' );
		}
		$ticketDateMax = date( 'Y-m-d', strtotime( '+60 days' ) );
		$disabledDays  = Yii::$app->params[ 'disabledDays' ];
		$openDays      = Yii::$app->params[ 'openDays' ];
		$disabledDates = Yii::$app->params[ 'disabledDates' ];
		if (( isset( $_GET[ 'mode' ] ) && $_GET[ 'mode' ] == 'admin') || Yii::$app->params[ 'allowOnDay' ]  ) {
			$ticketDateMin = date( 'Y-m-d' );
		}
		$soldoutDays = Tiket::find()->getDateSoldOut( $tourSelect, $ticketDateMin, $ticketDateMax );
		$session->close();
		return $this->render( 'index', [
			'tourSelect'    => $tourSelect,
			'peopleSelect'  => $peopleSelect,
			'ticketDate'    => $ticketDate,
			'ticketTime'    => $ticketTime,
			'ticketDateMin' => $ticketDateMin,
			'ticketDateMax' => $ticketDateMax,
			'soldoutDays'   => $soldoutDays,
			'disabledDays'  => $disabledDays,
			'disabledDates' => $disabledDates,
			'openDays'      => $openDays,
		] );
	}
	public function actionTiket() {
		$session = Yii::$app->session;
		$session->open();
		if ( Yii::$app->request->isPost ) {
			$session->set( 'tourSelect', $_POST[ 'tour-select' ] );
			$session->set( 'peopleSelect', $_POST[ 'people-select' ] );
			$session->set( 'ticketDate', $_POST[ 'ticketDate' ] );
			$session->set( 'ticketTime', $_POST[ 'ticketTime' ] );
		} else {
			if ( ! $session->has( 'tourSelect' ) ) {
				return $this->redirect( [ 'site/index' ] );
			}
		}
		$tourSelect   = $session->get( 'tourSelect' );
		$peopleSelect = $session->get( 'peopleSelect' );
		$ticketDate   = date( 'd/m/Y', strtotime( $session->get( 'ticketDate' ) ) );
		$ticketTime   = $session->get( 'ticketTime' );
		$hargaDewasa  = Yii::$app->params[ $tourSelect ][ 'adult' ];
		$hargaAnak    = Yii::$app->params[ $tourSelect ][ 'child' ];
		$session->close();
		$sisa = Tiket::find()->getSisaTimeSlot( $tourSelect, $session->get( 'ticketDate' ), $ticketTime );
		if ( in_array( $tourSelect, Yii::$app->params[ 'disabledTour' ] ) ) {
			$sisa = 0;
		}
		return $this->render( 'tiket', [
			'sisa'         => $sisa,
			'tourSelect'   => $tourSelect,
			'peopleSelect' => $peopleSelect,
			'ticketDate'   => $ticketDate,
			'ticketTime'   => $ticketTime,
			'hargaDewasa'  => $hargaDewasa,
			'hargaAnak'    => $hargaAnak,
		] );
	}
	private function calculate( $tourSelect, $qtyDewasa, $qtyAnak ) {
		$hargaDewasa = Yii::$app->params[ $tourSelect ][ 'adult' ];
		$hargaAnak   = Yii::$app->params[ $tourSelect ][ 'child' ];
		$totDewasa   = $qtyDewasa * $hargaDewasa;
		$totAnak     = $qtyAnak * $hargaAnak;
		$total       = $totDewasa + $totAnak;
		return [
			'totDewasa' => $totDewasa,
			'totAnak'   => $totAnak,
			'total'     => $total
		];
	}
	public function actionCheckout() {
		$session = Yii::$app->session;
		$session->open();
		if ( Yii::$app->request->isPost ) {
			$expiredTrial   = date( 'Y-m-d H:i:s', strtotime( Yii::$app->params[ 'durasiExpired' ] ) );
			$expired        = $expiredTrial;
			$maxExpired     = date( 'Y-m-d ' . Yii::$app->params[ 'maxTimeExpired' ] );
			$dateTimestamp1 = strtotime( $maxExpired );
			$dateTimestamp2 = strtotime( $expiredTrial );
			if ( $dateTimestamp2 > $dateTimestamp1 ) {
				$expired = date( 'Y-m-d', strtotime( ' +1 day' ) ) . ' ' . Yii::$app->params[ 'nextDayTimeExpired' ];
			}
			$session->set( 'qtyDewasa', $_POST[ 'qtyDewasa' ] );
			$session->set( 'qtyAnak', $_POST[ 'qtyAnak' ] );
			$session->set( 'completeName', $_POST[ 'completeName' ] );
			$session->set( 'handphone', $_POST[ 'handphone' ] );
			$session->set( 'emailAddress', $_POST[ 'emailAddress' ] );
			$session->set( 'city', $_POST[ 'city' ] );
			$session->set( 'country', $_POST[ 'country' ] );
			$session->set( 'expired', $expired );
//			$uuid = \thamtech\uuid\helpers\UuidHelper::uuid();
//			$session->set( 'tiket_id', $uuid );
			$model             = new Tiket;
			$model->tiket_id   = ( new \yii\db\Query )->select( new Expression( "uuid()" ) )->scalar();
			$model->no_booking = ( new \yii\db\Query )->select( new Expression( "UPPER(SUBSTRING(MD5(RAND()) FROM (FLOOR(RAND()*(23-1)+1)) FOR 10))" ) )->scalar();
			$model->tdate      = date( 'Y-m-d H:i:s' );
			$tourSelect        = $session->get( 'tourSelect' );
			if ( $tourSelect == '' ) {
				$this->redirect( [ 'site/index' ] );
				Yii::$app->end( 0 );
			}
			$ticketDate          = $session->get( 'ticketDate' );
			$ticketTime          = $session->get( 'ticketTime' );
			$hargaDewasa         = Yii::$app->params[ $tourSelect ][ 'adult' ];
			$hargaAnak           = Yii::$app->params[ $tourSelect ][ 'child' ];
			$qtyDewasa           = $session->get( 'qtyDewasa' );
			$qtyAnak             = $session->get( 'qtyAnak' );
			$peopleSelect        = ceil( ( $qtyDewasa + $qtyAnak ) / intval( Yii::$app->params[ 'timeslot' ][ 'perSlot' ] ) );
			$completeName        = $session->get( 'completeName' );
			$handphone           = $session->get( 'handphone' );
			$emailAddress        = $session->get( 'emailAddress' );
			$expired             = $session->get( 'expired' );
			$calc                = self::calculate( $tourSelect, $qtyDewasa, $qtyAnak );
			$model->jenis_tur    = $tourSelect;
			$model->jml          = $peopleSelect;
			$model->tiket_tgl    = $ticketDate;
			$model->tiket_jam    = $ticketTime;
			$model->dewasa       = $qtyDewasa;
			$model->anak         = $qtyAnak;
			$model->dewasa_harga = $hargaDewasa;
			$model->anak_harga   = $hargaAnak;
			$model->total        = $calc[ 'total' ];
			$model->nama_lengkap = $completeName;
			$model->no_hp        = $handphone;
			$model->email        = $emailAddress;
			$model->kota         = $session->get( 'city' );
			$model->negara       = $session->get( 'country' );
			$model->expired      = $expired;
			$model->save();
			$model->refresh();
			$valSlot = Tiket::find()->getSisaTimeSlot( $tourSelect, $session->get( 'ticketDate' ), $ticketTime );
			if ( $valSlot < 0 ) {
				Yii::$app->getSession()->setFlash( 'error', "Maaf, tiket sudah habis.. anda kurang cepat" );
				$model->delete();
				return $this->redirect( [ 'site/index' ] );
			}
			Yii::$app->mailer->compose( 'booking', [
				'no_booking'   => $model->no_booking,
				'tourSelect'   => $tourSelect,
				'peopleSelect' => $peopleSelect,
				'ticketDate'   => date( 'd/m/Y', strtotime( $ticketDate ) ),
				'ticketTime'   => $ticketTime,
				'hargaDewasa'  => $hargaDewasa,
				'hargaAnak'    => $hargaAnak,
				'qtyDewasa'    => $qtyDewasa,
				'qtyAnak'      => $qtyAnak,
				'totDewasa'    => $calc[ 'totDewasa' ],
				'totAnak'      => $calc[ 'totAnak' ],
				'total'        => $calc[ 'total' ],
				'completeName' => $completeName,
				'handphone'    => $handphone,
				'emailAddress' => $emailAddress,
				'expired'      => date( 'd/m/Y H:i:s', strtotime( $expired ) )
			] )
			                 ->setFrom( 'tickets@ullensentalu.com' )
			                 ->setTo( $emailAddress )
			                 ->setSubject( "Menunggu Pembayaran Reservasi Ullen Sentalu No {$model->no_booking}" ) // тема письма
//			                 ->setHtmlBody(print_r($_SESSION,true))
			                 ->send();
			$session->destroy();
			$session->close();
			return $this->render( 'checkout', [
				'no_booking'   => $model->no_booking,
				'tourSelect'   => $tourSelect,
				'peopleSelect' => $peopleSelect,
				'ticketDate'   => date( 'd/m/Y', strtotime( $ticketDate ) ),
				'ticketTime'   => $ticketTime,
				'hargaDewasa'  => $hargaDewasa,
				'hargaAnak'    => $hargaAnak,
				'qtyDewasa'    => $qtyDewasa,
				'qtyAnak'      => $qtyAnak,
				'totDewasa'    => $calc[ 'totDewasa' ],
				'totAnak'      => $calc[ 'totAnak' ],
				'total'        => $calc[ 'total' ],
				'completeName' => $completeName,
				'handphone'    => $handphone,
				'emailAddress' => $emailAddress,
				'expired'      => date( 'd/m/Y H:i:s', strtotime( $expired ) )
			] );
		}
		return $this->redirect( [ 'site/index' ] );
	}
//	public function actionCheckYourOrder() {
//		if ( Yii::$app->request->isPost ) {
//			$session = Yii::$app->session;
//			$session->open();
//			$session[ 'page_3' ] = [
//				"firstName"           => $_POST[ 'firstName' ],
//				"surName"             => $_POST[ 'surName' ],

views/site/_nav-bottom.php
<?php
use yii\helpers\Url;
$session = Yii::$app->session;
$session->open();
$isPage1Done = $session->has('page_1');
$isPage2Done = $session->has('page_2');
$isPage3Done = $session->has('page_3');
$isPage4Done = $session->has('page_4');
?>
<input id="form-token" type="hidden" name="<?=Yii::$app->request->csrfParam?>"
       value="<?=Yii::$app->request->csrfToken?>"/>
<nav class="nav-steps fixed-bottom fixed-bottom-extended">
	<div class="container">
		<div class="zone">
			<div class="col-xs-12 col-sm-9 steps">
				<div class="step <?=($step == 1? 'active':'')?> <?=($step != 1 && $isPage1Done? 'done':'')?>" id="navDateTime">
					<a href="<?=url::toRoute(['site/index'])?>">
						<p>1. <span class="hidden-xs">Plan your visit</span></p>
						<p class="sub hidden-xs" style="display: none; height: 34px; padding-top: 0px; margin-top: 15px; padding-bottom: 0px; margin-bottom: 15px;">
							<span id="navDate"><?=($isPage1Done ? date('d F', strtotime($session->get('page_1')['ticketDate'])) : '') ?></span>
							<span id="navTime"><?=($isPage1Done ? $session->get('page_1')['ticketTime'] : '') ?></span>
						</p>
					</a>
				</div>
				<div class="step <?=($step == 2? 'active':'')?> <?=($step != 2 && $isPage2Done? 'done':'')?>" id="navTicketsSummary">
                    <? if($isPage2Done) : ?><a href="<?=url::toRoute(['site/tiket'])?>"><?endif;?>
					<p>2. <span class="hidden-xs">Tickets</span></p>
                    <? if($isPage2Done) : ?>
                    <p class="sub hidden-xs" style="display: none; height: 119px; padding-top: 0px; margin-top: 15px; padding-bottom: 0px; margin-bottom: 15px;">
					<span id="navTickets">
                        <?=($session->get('page_2')['tickets']['ra'] > 0) ? $session->get('page_2')['tickets']['ra'].'x Adiluhung Mataram Adult<br>' : '' ?>
                        <?=($session->get('page_2')['tickets']['rc'] > 0) ? $session->get('page_2')['tickets']['rc'].'x Adiluhung Mataram Child<br>' : '' ?>
                        <?=($session->get('page_2')['tickets']['va'] > 0) ? $session->get('page_2')['tickets']['va'].'x Vorstenlanden Adult<br>' : '' ?>
                        <?=($session->get('page_2')['tickets']['vc'] > 0) ? $session->get('page_2')['tickets']['vc'].'x Vorstenlanden Child<br>' : '' ?>
                    </span>
                    </p>
                    <? endif; ?>
                    <? if($isPage2Done) : ?></a><?endif;?>
				</div>
				<div class="step <?=($step == 3? 'active':'')?> <?=($step != 3 && $isPage3Done? 'done':'')?>" id="navYourInformation">
                    <? if($isPage3Done) : ?><a href="<?=url::toRoute(['site/your-information'])?>"><?endif;?>
					<p>3. <span class="hidden-xs">Your information</span></p>
                    <p class="sub hidden-xs" style="display: none; height: 119px; padding-top: 0px; margin-top: 15px; padding-bottom: 0px; margin-bottom: 15px;">
					<span class="footer_mail">
                        <?=($isPage3Done) ? $session->get('page_3')['firstName'].' '.$session->get('page_3')['surName'].'<br>' : '' ?>
                        <?=($isPage3Done) ? $session->get('page_3')['emailAddressConfirm'] : '' ?>
                    </span>
                    </p>
					<? if($isPage3Done) : ?></a><?endif;?>
				</div>
				<div class="step <?=($step == 4? 'active':'')?> <?=($step != 4 && $isPage4Done? 'done':'')?>" id="navPayment">
                    <a href="<?=url::toRoute(['site/check-your-order'])?>">
					<p>4. <span class="hidden-xs">Payment</span></p>
                    </a>
				</div>
			</div>
            <? if($buttonText != '') : ?>
			<div class="col-xs-12 col-sm-3 ticket-button" style="">
				<a class="button btn-arrow-right btn-sec">
					<?=$buttonText;?>
                    <span class="icons icon-arrow-right"></span>
				</a>
			</div>
            <? endif; ?>
		</div>
	</div>
</nav>
<?php $session->close();

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/check-your-order.php
<?php
/* @var $this yii\web\View */
use yii\helpers\Url;
$this->title = 'Book your tickets - Ullen Sentalu Museum';
$session = Yii::$app->session;
$session->open();
$isPage1Done = $session->has('page_1');
$isPage2Done = $session->has('page_2');
$isPage3Done = $session->has('page_3');
$isPage4Done = $session->has('page_4');
?>
<script>
    var language = 'en';
    var jsDomain = '';
    var ticketDateMin = new Date(2020, 6, 20);
    var ticketDateMax = new Date(2020, 8, 30);
    var disabledDays = [];
    var disabledDates = [];
    var soldoutDays = ["2020-07-20"];
</script>

<form id="gt" method="post" action="https://tickets.vangoghmuseum.com/en/payment">
	<?= $this->render( '_nav-bottom', [
		'step' => 4,
		'buttonText' => ''
	] ) ?>
    <section class="ticket-zone">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 col-md-7">
                    <h2>Please check your order</h2>

                    <div class="row check-info">
                        <div class="col-sm-6">
                            <p><strong>Date &amp; time</strong>
                                <a href="<?=url::toRoute(['site/index'])?>" class="change-link">Change</a>
                            </p>
                            <p><?=($isPage1Done ? date('d F', strtotime($session->get('page_1')['ticketDate'])) : '') ?><br>
	                            <?=($isPage1Done ? $session->get('page_1')['ticketTime'] : '') ?></p>
                        </div>
                        <div class="col-sm-6">
                            <p><strong>Your information</strong> <a href="<?=url::toRoute(['site/your-information'])?>" class="change-link">Change</a></p>
                            <p><?=($isPage3Done) ? $session->get('page_3')['firstName'].' '.$session->get('page_3')['surName']:''?><br>
	                            <?=($isPage3Done) ? $session->get('page_3')['emailAddressConfirm'] : '' ?></p>
                        </div>
                    </div> <!-- row -->

                    <div class="tickets check-zone">
                        <div class="row">
                            <div class="ticket__header cf">
                                <div class="col-md-12">
                                    <p><strong>Tickets</strong> <a href="<?=url::toRoute(['site/tiket'])?>" class="change-link">Change</a></p>
                                </div>
                            </div> <!-- ticket__header -->
                        </div> <!-- row -->
                        <div class="row">
                            <div class="ticket__cat cf">
	                            <?if($session->get('page_2')['tickets']['ra'] > 0):?>
                                <div class="col-xs-7 col-sm-8">
                                    <span class="pull-left">Adiluhung Mataram Adult</span>
                                    <span class="pull-right">x <?=$session->get('page_2')['tickets']['ra']?></span>
                                </div>
                                <div class="col-xs-5 col-sm-4">
                                    <p class="text--right">Rp<?=number_format(Yii::$app->params['ra']*$session->get('page_2')['tickets']['ra'],0,',','.')?></p>
                                </div>
	                            <?endif;?>
	                            <?if($session->get('page_2')['tickets']['rc'] > 0):?>
                                <div class="col-xs-7 col-sm-8">
                                    <span class="pull-left">Adiluhung Mataram Child</span>
                                    <span class="pull-right">x <?=$session->get('page_2')['tickets']['rc']?></span>
                                </div>
                                <div class="col-xs-5 col-sm-4">
                                    <p class="text--right">Rp<?=number_format(Yii::$app->params['rc']*$session->get('page_2')['tickets']['rc'],0,',','.')?></p>
                                </div>
	                            <?endif;?>
	                            <?if($session->get('page_2')['tickets']['va'] > 0):?>
                                <div class="col-xs-7 col-sm-8">
                                    <span class="pull-left">Vorstenlanden Adult</span>
                                    <span class="pull-right">x <?=$session->get('page_2')['tickets']['va']?></span>
                                </div>
                                <div class="col-xs-5 col-sm-4">
                                    <p class="text--right">Rp<?=number_format(Yii::$app->params['va']*$session->get('page_2')['tickets']['va'],0,',','.')?></p>
                                </div>
	                            <?endif;?>
	                            <?if($session->get('page_2')['tickets']['vc'] > 0):?>
                                <div class="col-xs-7 col-sm-8">
                                    <span class="pull-left">Vorstenlanden Child</span>
                                    <span class="pull-right">x <?=$session->get('page_2')['tickets']['vc']?></span>
                                </div>
                                <div class="col-xs-5 col-sm-4">
                                    <p class="text--right">Rp<?=number_format(Yii::$app->params['vc']*$session->get('page_2')['tickets']['vc'],0,',','.')?></p>
                                </div>
	                            <?endif;?>
                            </div> <!-- ticket__cat -->
                        </div>
                        <div class="row">
                            <div class="ticket__cat cf ticket__borderless">
                            </div>
                        </div>

                        <div class="row">
                            <div class="ticket__cat cf ticket__borderless">
                            </div>
                        </div>

                        <div class="row">
                            <div class="ticket__subtotal cf ticket__borderless">
                                <div class="col-xs-7 col-sm-8">
                                    <p><strong>Total</strong></p>
                                </div>
                                <div class="col-xs-5 col-sm-4">
                                    <p class="text--right"><strong>Rp<?=number_format($session->get('page_2')['total'],0,',','.')?></strong></p>
                                </div>
                            </div> <!-- ticket__subtotal -->
                        </div> <!-- row -->

                    </div> <!-- tickets -->
                    <button class="adyen-checkout__button adyen-checkout__button--pay" type="button">
                        <span class="adyen-checkout__button__content">
                            <img class="adyen-checkout__button__icon" src="https://checkoutshopper-live.adyen.com/checkoutshopper/images/components/lock.svg" alt="Icon" aria-hidden="true" role="presentation">
                            <span class="adyen-checkout__button__text">Pay Rp<?=number_format($session->get('page_2')['total'],0,',','.')?></span>
                        </span>
                    </button>
                    <br style="clear:both;">
                </div>

                <div class="col-sm-12 col-md-5">

                </div>
            </div>

        </div>
    </section>			<footer class="footer">

    </footer>
</form>
<?php $session->close();

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/login.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
$this->title                     = 'Login';
$this->params[ 'breadcrumbs' ][] = $this->title;
?>
<section class="ticket-zone">
    <div class="container">
        <div class="site-login">
            <h1><?= Html::encode( $this->title ) ?></h1>
            <p>Please fill out the following fields to login:</p>
			<?php $form = ActiveForm::begin( [
				'id'          => 'login-form',
				'layout'      => 'horizontal',
				'fieldConfig' => [
					'template'     => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
					'labelOptions' => [ 'class' => 'col-lg-1 control-label' ],
				],
			] ); ?>

			<?= $form->field( $model, 'username' )->textInput( [ 'autofocus' => true ] ) ?>

			<?= $form->field( $model, 'password' )->passwordInput() ?>

			<?= $form->field( $model, 'rememberMe' )->checkbox( [
				'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
			] ) ?>
            <div class="form-group">
                <div class="col-lg-offset-1 col-lg-11">
					<?= Html::submitButton( 'Login', [ 'class' => 'btn btn-primary', 'name' => 'login-button' ] ) ?>
                </div>
            </div>
			<?php ActiveForm::end(); ?>
            <!--    <div class="col-lg-offset-1" style="color:#999;">-->
            <!--        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>-->
            <!--        To modify the username/password, please check out the code <code>app\models\User::$users</code>.-->
            <!--    </div>-->
        </div>
    </div>
</section>